<a href="https://colab.research.google.com/github/nisadar-code/myCode/blob/main/Random_Forests.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Dataset: diabetes.xlsx

# Step 1: Import LIbraries

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [1]:
# Step 2: Upload the Excel file
print("Please upload diabetes.xlsx")
from google.colab import files
uploaded = files.upload()

Please upload diabetes.xlsx

In [ ]:
# STEP 3: Read and view the Excel file


df = pd.read_excel('diabetes.xlsx')
print("Data loaded successfully!")
display(df)

Data loaded successfully!

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,Class
0,1,85,66,29,0,26.6,0.351,31,0,Healthy
1,1,89,66,23,94,28.1,0.167,21,0,Healthy
2,5,116,74,0,0,25.6,0.201,30,0,Healthy
3,10,115,0,0,0,35.3,0.134,29,0,Healthy
4,4,110,92,0,0,37.6,0.191,30,0,Healthy
...,...,...,...,...,...,...,...,...,...,...
763,1,128,88,39,110,36.5,1.057,37,1,Diabetic
764,0,123,72,0,0,36.3,0.258,52,1,Diabetic
765,6,190,92,0,0,35.5,0.278,66,1,Diabetic
766,9,170,74,31,0,44.0,0.403,43,1,Diabetic
767,1,126,60,0,0,30.1,0.349,47,1,Diabetic

In [ ]:
# Target variable
y = df['Class']

# Drop numeric and categorical targets
X = df.drop(['Outcome','Class'], axis=1)

In [ ]:
# Split data

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [ ]:
# Train Random Forest

model = RandomForestClassifier(
    n_estimators=50,
    max_features=3,
    min_samples_split=10,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(max_features=3, min_samples_split=10, n_estimators=50,
                       random_state=42)

In [ ]:
# Predict target

y_pred = model.predict(X_test)

In [ ]:
# Model Evaluation

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.7662337662337663

In [ ]:
# Feature Importance

importances = pd.Series(model.feature_importances_, index=X.columns)
importances.sort_values(ascending=False).head(10)

Glucose                     0.321008
BMI                         0.187975
Age                         0.134037
DiabetesPedigreeFunction    0.106702
BloodPressure               0.074173
Insulin                     0.063291
Pregnancies                 0.057486
SkinThickness               0.055328
dtype: float64

In [ ]:
# Compare with Decision Tree

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(
    max_features=3,
    min_samples_split=10,
    random_state=42
    )
dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)

print("Decision Tree's Accuracy:", accuracy_score(y_test, dt_pred))

Decision Tree's Accuracy: 0.7012987012987013

In [ ]:
# Predict the class of an unlabelled given record

data = pd.DataFrame({
    'Pregnancies': [2],
    'Glucose': [120],
    'BloodPressure': [70],
    'SkinThickness': [20],
    'Insulin': [85],
    'BMI': [28.5],
    'DiabetesPedigreeFunction': [0.45],
    'Age': [35]
})


new_record = data[X.columns] # Select and reorder columns

# Predict
prediction = model.predict(new_record)

# If you want probability
probability = model.predict_proba(new_record)

print("Predicted Class:", prediction[0])
print("Prediction Probabilities:", probability[0])

Predicted Class: Healthy
Prediction Probabilities: [0.43508604 0.56491396]